title: NPML
description: A website for our NPML project.
theme: just-the-docs

url: https://zhtdbb1.github.io/FindingGhostParticles

aux_links:
  Github Repository: https://github.com/axie0927/FindingGhostParticles-RegressionSubgroup

# Add custom CSS file
just_the_docs:

  # Enable Just the Docs built-in responsive menu
  nav_enabled: true
  search_enabled: true

  

nav_order: true

# Sidebar structure
nav:

  - title: "Data"
    url: /data
    children:
      - title: "Data Preprocessing"
        url: /data_preprocessing
      - title: "Parameters"
        url: /parameters

  - title: "Methods"
    url: /methods
    children:
      - title: "Classification Group"
        url: /classification
      - title: "Regression Group"
        url: /regression

  - title: "Conclusion"
    url: /conclusion

  - title: "About Us"
    url: /about_us