title: Finding Ghost Particles (Regression Group)
description: A website for our NPML project.
theme: just-the-docs

url: https://zhtdbb1.github.io/FindingGhostParticles

aux_links:
  Github Repository: https://github.com/axie0927/FindingGhostParticles-RegressionSubgroup
